### model
model_name_or_path: llava-hf/llava-1.5-7b-hf
visual_inputs: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8

### dataset
dataset: mm_ac_train_LL-1000
eval_dataset: mm_ac_val_LL
template: vicuna
cutoff_len: 4096
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: saves/aug28_llava_mm_ac_train_LL-1000/
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 10000.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
ddp_find_unused_parameters: false
upcast_layernorm: true

### eval
#val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100

report_to: wandb
run_name: aug28_llava_mm_ac_train_LL-1000


