### model
#model_name_or_path: ISTA-DASLab/Meta-Llama-3-8B-Instruct-AQLM-2Bit-1x16
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
quantization_bit: 8
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 64

### dataset
dataset: preempt_v2_ac_train_LL-all
eval_dataset: preempt_v2_ac_val_LL
template: llama3
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /results/saves/multinode_sep5_ac_train_LL-all_bs256/  # make sure to prefix /results when running with gantry
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 10000.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
ddp_find_unused_parameters: false
upcast_layernorm: true
resume_from_checkpoint: true

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100

report_to: wandb
run_name: multinode_sep5_ac_train_LL-all_bs256


